# Your Solution
version: '3'
services:
   
  book-library:
    platform: linux/amd64 
    image: bookf
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: bookf
    ports:
     - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://sit7229_2_user:7T2SYtruiZEEQc8ElZD6Lr0AZX9ZDBCJ@dpg-crqkej68ii6s73d0bo50-a.oregon-postgres.render.com/sit7229_2
    restart: "no"

  book-inventory:
    platform: linux/amd64 
    image: inventoryf
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventoryf
    ports:
     - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://sit7229_2_user:7T2SYtruiZEEQc8ElZD6Lr0AZX9ZDBCJ@dpg-crqkej68ii6s73d0bo50-a.oregon-postgres.render.com/sit7229_2
    restart: "no"
