# Your Solution
#deployment details for loading deakin-library image
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookf
  template:
    metadata:
      labels:
        app: bookf
    spec:
      containers:
        - name: bookf
          image: task9darsh.azurecr.io/bookf:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              value: "postgresql://sit7229_2_user:7T2SYtruiZEEQc8ElZD6Lr0AZX9ZDBCJ@dpg-crqkej68ii6s73d0bo50-a.oregon-postgres.render.com/sit7229_2"
---
apiVersion: v1
kind: Service
metadata:
  name: bookf
spec:
  selector:
    app: bookf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 8080

---
#deployment details for loading deakin-library image (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventoryf
  labels:
    app: inventoryf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventoryf
  template:
    metadata:
      labels:
        app: inventoryf
    spec:
      containers:
        - name: inventoryf
          image: task9darsh.azurecr.io/inventoryf:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgresql://sit7229_2_user:7T2SYtruiZEEQc8ElZD6Lr0AZX9ZDBCJ@dpg-crqkej68ii6s73d0bo50-a.oregon-postgres.render.com/sit7229_2"
---
apiVersion: v1
kind: Service
metadata:
  name: inventoryf
spec:
  selector:
    app: inventoryf
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 8081
